//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalHelperMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BedTable
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Bed ID is Required")]
        [Display(Name = "Bed ID")]
        public string BedID { get; set; }

        [Required(ErrorMessage = "Ward No. is Required")]
        [Display(Name = "Ward No.")]
        public Nullable<int> Ward_No { get; set; }

        [Required(ErrorMessage = "Ward Type is Required")]
        [Display(Name = "Ward Type")]
        public string Ward_type { get; set; }
    }
}
