//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalHelperMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorDept
    {
        public int DoctDeptID { get; set; }
        public string Doctor_name { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Speciality { get; set; }
    }
}
