//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalHelperMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DoctorTable
    {
        public int DoctorID { get; set; }

        [Required(ErrorMessage = "Doctor Name is Required")]
        [Display(Name = "Doctor Name")]
        public string Doctor_name { get; set; }
        public string Department { get; set; }
        public string Availability { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
